### ISSUE TITLE
Problem with installing the package

### ISSUE THREAD

**Issue by martynabogacz** [afrimapr/afrilearndata#4]
I tried to install afrileardata package using 
```
remotes::install_github("afrimapr/afrilearndata")
```
However, it fails and the following error message appears: 
```
Error: (converted from warning) Setting LC_CTYPE= failed
Execution halted
Error: Failed to install 'afrilearndata' from GitHub:
  (converted from warning) installation of package 'C:/Users/files/AppData/Local/Temp/RtmpIvBkbT/file3b44191f27f2/afrilearndata_0.0.0.9000.tar.gz' had non-zero exit status
```

I suspect is something to do with the R locale but I can't solve it. Did anybody have similar issue?

**Comment by andysouth** [comment]
Hi @martynabogacz I'm assuming this issue resolved itself, so closing. We can re-open if still a problem.
